# LLM API测试配置模板
# 请复制此文件为config.yaml并填入实际的API密钥

platforms:
  openai:
    enabled: true
    api_key: "your-openai-api-key"
    base_url: "https://api.openai.com/v1"  # 可选，用于自定义endpoint
    models:
      - name: "gpt-3.5-turbo"
        max_tokens: 1000
        temperature: 0.7
      - name: "gpt-4"
        max_tokens: 1000
        temperature: 0.7

  anthropic:
    enabled: true
    api_key: "your-anthropic-api-key"
    models:
      - name: "claude-3-sonnet-20240229"
        max_tokens: 1000
        temperature: 0.7
      - name: "claude-3-opus-20240229"
        max_tokens: 1000
        temperature: 0.7

  baidu:
    enabled: true
    api_key: "your-baidu-api-key"
    secret_key: "your-baidu-secret-key"
    models:
      - name: "ERNIE-Bot-4"
        max_tokens: 1000
        temperature: 0.7

  alibaba:
    enabled: true
    api_key: "your-alibaba-api-key"
    models:
      - name: "qwen-max"
        max_tokens: 1000
        temperature: 0.7

  zhipu:
    enabled: true
    api_key: "your-zhipu-api-key"
    models:
      - name: "glm-4"
        max_tokens: 1000
        temperature: 0.7

# 测试配置
test_settings:
  # 测试提示词
  test_prompts:
    - prompt: "你好，请介绍一下你自己"
      category: "basic"
    - prompt: "请解释什么是机器学习"
      category: "knowledge"
    - prompt: "编写一个Python函数计算斐波那契数列"
      category: "coding"
    - prompt: "分析一下当前人工智能的发展趋势"
      category: "reasoning"
  
  # 超时设置（秒）
  timeout: 60
  
  # 重试次数
  max_retries: 3
  
  # 结果保存路径
  results_path: "results/"
  
  # 是否保存详细响应
  save_detailed_responses: true